"""
ML Prediction API — FastAPI application.
Auto-generated by AI Data Science Copilot.
"""

import logging
from contextlib import asynccontextmanager
from typing import Any, Dict

from fastapi import FastAPI, HTTPException, Request, status
from fastapi.middleware.cors import CORSMiddleware

from predictor import (
    check_drift,
    explain_prediction,
    predict_batch,
    predict_single,
)
from schemas import (
    BatchPredictionInput,
    BatchPredictionOutput,
    DriftReport,
    ExplainOutput,
    HealthResponse,
    PredictionInput,
    PredictionOutput,
)

# ── Logging ────────────────────────────────────────────────────────────────────
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ── Global model registry ──────────────────────────────────────────────────────
_MODEL_DATA: Dict[str, Any] = {}
MODEL_PATH = "saved_models\api_model_20260411_172352.joblib"


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Load the model on startup; release resources on shutdown."""
    logger.info("Loading model from %s …", MODEL_PATH)
    try:
        import joblib
        data = joblib.load(MODEL_PATH)
    except Exception:
        import pickle
        with open(MODEL_PATH, "rb") as fh:
            data = pickle.load(fh)

    _MODEL_DATA.update(data)
    logger.info("Model loaded — class: %s", data.get("model_class", "unknown"))
    yield
    _MODEL_DATA.clear()
    logger.info("Model unloaded.")


# ── Application ────────────────────────────────────────────────────────────────
app = FastAPI(
    title="ML Prediction API",
    description=(
        "Auto-generated prediction service with confidence scores, "
        "per-class probabilities, feature explanations, and drift detection."
    ),
    version="2.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Utility ────────────────────────────────────────────────────────────────────
def _require_model():
    if not _MODEL_DATA:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Model not loaded.",
        )


# ── Endpoints ──────────────────────────────────────────────────────────────────
@app.get("/", tags=["info"])
def read_root():
    return {
        "service":    "ML Prediction API",
        "version":    "2.0.0",
        "status":     "active",
        "model":      _MODEL_DATA.get("model_class"),
        "endpoints":  ["/health", "/model_info", "/predict",
                       "/predict_batch", "/explain", "/drift"],
    }


@app.get("/health", response_model=HealthResponse, tags=["info"])
def health_check():
    """Liveness probe."""
    return HealthResponse(
        status     = "healthy" if _MODEL_DATA else "degraded",
        model_loaded = bool(_MODEL_DATA),
        model_class  = _MODEL_DATA.get("model_class"),
        has_proba    = bool(_MODEL_DATA.get("has_proba")),
    )


@app.get("/model_info", tags=["info"])
def get_model_info():
    """Return model metadata and feature list."""
    _require_model()
    return {
        "model_class":   _MODEL_DATA.get("model_class"),
        "feature_names": _MODEL_DATA.get("feature_names", ['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS', 'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope']),
        "has_proba":     _MODEL_DATA.get("has_proba"),
        "metadata":      _MODEL_DATA.get("metadata", {}),
        "saved_at":      _MODEL_DATA.get("saved_at"),
    }


@app.post("/predict", response_model=PredictionOutput, tags=["prediction"])
def predict(input_data: PredictionInput):
    """
    Single prediction with confidence score, per-class probabilities,
    and a plain-English interpretation.
    """
    _require_model()
    try:
        result = predict_single(_MODEL_DATA, input_data.model_dump())
    except Exception as exc:
        logger.exception("Prediction failed")
        raise HTTPException(status_code=500, detail=str(exc))

    return PredictionOutput(
        prediction     = result["prediction"],
        confidence     = result["confidence"],
        interpretation = result["interpretation"],
        probabilities  = result.get("probabilities"),
        model_name     = _MODEL_DATA.get("model_class", "model"),
        latency_ms     = result.get("latency_ms"),
    )


@app.post("/predict_batch", response_model=BatchPredictionOutput, tags=["prediction"])
def predict_batch_endpoint(input_data: BatchPredictionInput):
    """
    Batch predictions.  Returns per-row predictions, confidences,
    and (if the model supports it) per-class probabilities.
    """
    _require_model()
    if not input_data.inputs:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="inputs list must not be empty.",
        )
    try:
        result = predict_batch(_MODEL_DATA, input_data.inputs)
    except Exception as exc:
        logger.exception("Batch prediction failed")
        raise HTTPException(status_code=500, detail=str(exc))

    return BatchPredictionOutput(
        predictions  = result["predictions"],
        confidences  = result["confidences"],
        probabilities = result.get("probabilities"),
        count        = result["count"],
        latency_ms   = result.get("latency_ms"),
    )


@app.post("/explain", response_model=ExplainOutput, tags=["explainability"])
def explain(input_data: PredictionInput):
    """
    Return per-feature contributions to the prediction using coefficient /
    feature-importance attribution.
    """
    _require_model()
    try:
        result = explain_prediction(_MODEL_DATA, input_data.model_dump())
    except Exception as exc:
        logger.exception("Explanation failed")
        raise HTTPException(status_code=500, detail=str(exc))

    return ExplainOutput(**result)


@app.post("/drift", response_model=DriftReport, tags=["monitoring"])
def drift_check(input_data: PredictionInput):
    """
    Compare incoming feature values against the training distribution.
    Flags features whose z-score exceeds 3σ from the training mean.
    """
    _require_model()
    result = check_drift(_MODEL_DATA, input_data.model_dump())
    return DriftReport(**result)


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=False)
